apiVersion: v1
kind: Service
metadata:
  name: {{ include "diameter-dra.fullname" . }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ include "diameter-dra.name" . }}
  ports:
    - name: diameter
      port: 3868
    - name: diameter-secure
      port: 3869